name: Build and Deploy Single Web App (Auto Blue-Green)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: python-app
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------- Checkout Code -------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for Terraform module downloads
        run: |
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      # ------------------- Login to Azure -------------------
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ------------------- Login to ACR -------------------
      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # ------------------- Build and Push Docker Image -------------------
      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          az acr build --registry ${{ secrets.ACR_NAME }} \
            --image $IMAGE_NAME:$IMAGE_TAG \
            --image $IMAGE_NAME:latest .

      # ------------------- Setup Terraform -------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5  # or your desired version

      # ------------------- Terraform Init -------------------
      - name: Terraform Init
        working-directory: terraformv3/examples/complete/container_platform
        run: terraform init

      # ------------------- Terraform Plan -------------------
      - name: Terraform Plan
        working-directory: terraformv3/examples/complete/container_platform
        run: terraform plan -out=tfplan

      # ------------------- Terraform Apply -------------------
      - name: Terraform Apply
        working-directory: terraformv3/examples/complete/container_platform
        run: terraform apply -auto-approve tfplan

      # ------------------- Determine Idle Slot -------------------
      - name: Determine Idle Slot
        id: idle-slot
        run: |
          RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}
          APP_NAME=${{ secrets.AZURE_APP_NAME }}

          PROD_IMAGE=$(az webapp config container show \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --query "linuxFxVersion" -o tsv)

          SLOT_BLUE_IMAGE=$(az webapp config container show --name $APP_NAME --resource-group $RESOURCE_GROUP --slot blue --query "linuxFxVersion" -o tsv)
          SLOT_GREEN_IMAGE=$(az webapp config container show --name $APP_NAME --resource-group $RESOURCE_GROUP --slot green --query "linuxFxVersion" -o tsv)

          if [[ "$SLOT_BLUE_IMAGE" == "$PROD_IMAGE" ]]; then
            IDLE_SLOT="green"
          else
            IDLE_SLOT="blue"
          fi

          echo "slot_name=$IDLE_SLOT" >> $GITHUB_ENV
          echo "Idle slot chosen: $IDLE_SLOT"

      # ------------------- Deploy to Idle Slot -------------------
      - name: Deploy to Idle Slot
        run: |
          IMAGE_TAG=${{ github.run_number }}
          RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}
          APP_NAME=${{ secrets.AZURE_APP_NAME }}
          SLOT_NAME=$slot_name

          az webapp config container set \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --slot $SLOT_NAME \
            --docker-custom-image-name "${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$IMAGE_TAG" \
            --docker-registry-server-managed-identity true

      # ------------------- Swap Idle Slot to Production -------------------
      - name: Swap Slot to Production
        run: |
          RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}
          APP_NAME=${{ secrets.AZURE_APP_NAME }}
          SLOT_NAME=$slot_name

          az webapp deployment slot swap \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --slot $SLOT_NAME
