name: Build and Deploy Web App (Blue/Green with Auto-Swap)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: python-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for Terraform module downloads
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Determine Deployment Slot (Blue/Green)
        id: slot
        run: |
          # Toggle deployment slot
          LAST_SLOT_FILE=".last_slot"
          if [ -f "$LAST_SLOT_FILE" ]; then
            LAST_SLOT=$(cat $LAST_SLOT_FILE)
            if [ "$LAST_SLOT" == "blue" ]; then
              echo "green" > $LAST_SLOT_FILE
              echo "slot=green" >> $GITHUB_OUTPUT
            else
              echo "blue" > $LAST_SLOT_FILE
              echo "slot=blue" >> $GITHUB_OUTPUT
            fi
          else
            echo "blue" > $LAST_SLOT_FILE
            echo "slot=blue" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker image to ACR
        run: |
          IMAGE_TAG=${{ github.run_number }}
          az acr build --registry ${{ secrets.ACR_NAME }} \
            --image ${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            --image ${{ env.IMAGE_NAME }}:latest .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: terraformv3/examples/complete/container_platform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraformv3/examples/complete/container_platform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform plan \
            -var="image_tag=${{ github.run_number }}" \
            -var="slot_name=${{ steps.slot.outputs.slot }}" \
            -var="acr_login_server=${{ secrets.ACR_LOGIN_SERVER }}" \
            -var="image_name=${{ env.IMAGE_NAME }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: terraformv3/examples/complete/container_platform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve tfplan
